In [1]:
import numpy as np

In [2]:
a =  np.array([['a','b','c'],
               ['d','e','f']])

In [3]:
n = a[a == 'b']

# Empty Array Replace


In [6]:
a = np.empty([5,5])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        9.45699680e-308, 1.11261027e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306],
       [7.56599128e-307, 1.78022206e-306, 8.34451503e-308,
        2.22507386e-306, 2.56765117e-312]])

In [8]:
a_i = a

In [12]:
for i in range(len(a)):
    for j in range(len(a[0])):
        a_i[i][j] = int(input(':'))

In [13]:
a_i

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [21]:
for x in range(len(a[0])):
    a_i[0][x] = input(':')

In [22]:
a_i

array([[-1., -2., -3., -4., -5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [26]:
sum_0 = sum(a_i[0])
sum_0

-15.0

In [28]:
mean_0 = np.average(a_i[0])
mean_0

-3.0

In [30]:
mean = np.average(a_i)
mean

11.8

# Vector

In [31]:
from typing import List

In [32]:
Vector = List[float]

In [42]:
def add(v:Vector , w:Vector) -> Vector :
    return [v_i + w_i for v_i,w_i in zip(v,w)]

In [43]:
add([1,2,3],[4,5,6])

[5, 7, 9]

In [44]:
def minus(v:Vector , w:Vector ) -> Vector:
    assert len(v) == len(w) , 'Different Size!!'
    return [v_i - w_i for v_i,w_i in zip(v,w)]

In [45]:
minus([1,2,3],[4,5,6])

[-3, -3, -3]

In [51]:
def sum_vector(vectors : List[Vector]) -> Vector:
    num_elements = len(vectors[0])
    assert all(len(v) == num_elements for v in vectors)
    return [sum(vector[i] for vector in vectors) for i in range(num_elements)]

In [52]:
sum_vector([[1,2,3],[4,5,6],[7,8,9]])

[12, 15, 18]

In [65]:
list1 = []

In [61]:
def input01():
    n = int(input(':'))
    for i in range(n):
        list1.append(int(input(':')))
        

In [66]:
input01()

In [67]:
list1

[6, 7, 8, 9, 10]

หา ฐานนิยม

In [85]:
from collections import Counter

In [89]:

def mode(xs: List[float]) -> float :
    counts = Counter(xs)
    max_count = max(counts.values())
    return [x_i for x_i,count in counts.items() if count == max_count  ]
    
                

In [90]:
mode([2,2,2,2,4,5,6,7])

[2]

In [1]:
from IPython.display   import IFrame,YouTubeVideo,SVG,HTML

In [4]:
IFrame('https://www.gstatic.com/education/formulas2/443397389/en/sample_variance.svg',width=800,height=400)