# Matrix 

Matrix == array 2D

Suqare Matrix : Matrix ที่มิติเท่ากัน

In [1]:
import numpy as np

# Zero Matrix

np.zeros(size) สามารถกำหนด dtype ได้

In [3]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

np.zeros([row,col]))

In [4]:
np.zeros([3,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones Matrix

In [5]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Matrix Full

np.full(จำนวน,ค่า)

In [7]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [8]:
np.full([5,5],10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Matrix Empty

In [9]:
np.empty([3,4])

array([[1.06171802e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 3.06134235e-057, 2.80246839e-032,
        4.81700581e-038],
       [2.35742472e+184, 9.20226046e+169, 2.32004978e-056,
        2.73949138e-057]])

* Ex การใช้

In [26]:
A = np.empty([3,3])
A

array([[4.67296746e-307, 1.69121096e-306, 9.34609111e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306],
       [6.23057349e-307, 1.42419530e-306, 0.00000000e+000]])

In [27]:
for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = int(input(':'))
    
    

In [28]:
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# Identity Matrix

In [13]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

* ถ้าหากต้องการกำหนดขนาด ให้เปลี่ยนไปใช้ np.eye(size)

In [14]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

* ย้ายตำแหน่งเส้น 1  ให้กำหนดค่า k

In [15]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

# Linspace

array 1 มิติ ที่สามารถระบุจำนวน,ช่วง,สมาชิก

* np.linspace(start,stop,number)

In [16]:
np.linspace(1,10,10,dtype= int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Arange

* np.arange(start,stop,step)

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(-6,7)

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

# Random

* np.random.module(size)

In [47]:
np.random.random([3,3])

array([[0.36305378, 0.54607789, 0.43421519],
       [0.43829613, 0.49622032, 0.73824578],
       [0.6650156 , 0.96611423, 0.49811231]])

In [45]:
np.random.randint(10 , size =[3,3])

array([[9, 3, 7],
       [7, 7, 1],
       [3, 7, 6]])

# NumPy Attribute

* บอกว่ามีกี่มิติ ด้วยคำสั่ง .ndim

In [54]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [55]:
a.ndim

2

In [56]:
a.shape

(3, 3)

In [57]:
a.dtype

dtype('int32')

In [58]:
a.size

9

* Bytes / 8 Bytes


In [59]:
a.itemsize

4

# Slice

A[i] :Rows 
  

A[i][j] :Column

* 1D

a[start,end,step]

In [61]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
print(a[1] ,' ', a[:] ,' ',a[5:] ,' ', a[:3] )

2   [ 1  2  3  4  5  6  7  8  9 10]   [ 6  7  8  9 10]   [1 2 3]


* 2D

x[start,end,step,col]

x[row,col]

In [69]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [74]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

# Index Operator

In [2]:
x = np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
index = np.array([2,4,6,8])

array([2, 4, 6, 8])

In [6]:
x[index]

array([3, 5, 7, 9])

In [8]:
y = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [11]:
y[[0,2],[2,0]]

array([3, 7])

In [13]:
x[[1,4,1,4,1,4]]

array([2, 5, 2, 5, 2, 5])

In [21]:
y[[1,2],[2,1]]


array([6, 8])

In [26]:
x[x>2]+100

array([103, 104, 105, 106, 107, 108, 109])

# Math

สามารถนำทุกตัวใน array ไปดำเนินการทำคณิตศาสตร์ได้

In [28]:
a = np.arange(1,5)

array([1, 2, 3, 4])

In [29]:
a+5

array([6, 7, 8, 9])

In [32]:
a[a % 2 ==0]

array([2, 4])

In [34]:
print(min(a),'',max(a))

1  4
