# Matrix 

Matrix == array 2D

Suqare Matrix : Matrix ที่มิติเท่ากัน

In [2]:
import numpy as np

# Zero Matrix

np.zeros(size) สามารถกำหนด dtype ได้

In [3]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

np.zeros([row,col]))

In [4]:
np.zeros([3,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones Matrix

In [5]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Matrix Full

np.full(จำนวน,ค่า)

In [7]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [8]:
np.full([5,5],10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Matrix Empty

In [9]:
np.empty([3,4])

array([[1.06171802e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 3.06134235e-057, 2.80246839e-032,
        4.81700581e-038],
       [2.35742472e+184, 9.20226046e+169, 2.32004978e-056,
        2.73949138e-057]])

* Ex การใช้

In [26]:
A = np.empty([3,3])
A

array([[4.67296746e-307, 1.69121096e-306, 9.34609111e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306],
       [6.23057349e-307, 1.42419530e-306, 0.00000000e+000]])

In [27]:
for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = int(input(':'))
    
    

In [28]:
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# Identity Matrix

In [13]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

* ถ้าหากต้องการกำหนดขนาด ให้เปลี่ยนไปใช้ np.eye(size)

In [14]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

* ย้ายตำแหน่งเส้น 1  ให้กำหนดค่า k

In [15]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

# Linspace

array 1 มิติ ที่สามารถระบุจำนวน,ช่วง,สมาชิก

* np.linspace(start,stop,number)

In [16]:
np.linspace(1,10,10,dtype= int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Arange

* np.arange(start,stop,step)

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(-6,7)

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])