# Matrix 

Matrix == array 2D

Suqare Matrix : Matrix ที่มิติเท่ากัน

In [60]:
import numpy as np

# Zero Matrix

np.zeros(size) สามารถกำหนด dtype ได้

In [61]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

np.zeros([row,col]))

In [62]:
np.zeros([3,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones Matrix

In [63]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [64]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Matrix Full

np.full(จำนวน,ค่า)

In [65]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [66]:
np.full([5,5],10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Matrix Empty

In [67]:
np.empty([3,4])

array([[7.51626587e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 1.31370903e-076, 5.49799288e-090,
        1.83119742e-076],
       [4.28893826e-038, 4.47130196e-033, 3.99910963e+252,
        1.90979636e-312]])

* Ex การใช้

In [79]:
A = np.empty([5,4])
A

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307],
       [1.02360935e-306, 1.69120416e-306, 1.78022342e-306,
        6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11261027e-306,
        1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306]])

In [81]:
for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = int(input(':'))
    
    

In [82]:
A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 19., 19., 20.]])

# Identity Matrix

In [ ]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

* ถ้าหากต้องการกำหนดขนาด ให้เปลี่ยนไปใช้ np.eye(size)

In [ ]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

* ย้ายตำแหน่งเส้น 1  ให้กำหนดค่า k

In [ ]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

# Linspace

array 1 มิติ ที่สามารถระบุจำนวน,ช่วง,สมาชิก

* np.linspace(start,stop,number)

In [ ]:
np.linspace(1,10,10,dtype= int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])