# 1D

In [1]:
import numpy as np

In [2]:
a = np.array([10,5,4,6,99,100,50,30])

In [3]:
a.sum() #ผลรวมมาชิก

304

In [4]:
a.prod() # ผลคูณสมาชิก

640130816

In [5]:
a.mean()

38.0

In [6]:
a.max()

100

In [7]:
a.min()

4

In [8]:
a.argmax() #ระบุตำแหน่ง ที่เก็บค่ามากที่สุดใน array 

5

# 2D


axis 0 = แนวตั้ง

axis 1 = แนวนอน

In [10]:
b = np.array([[10,20,30],[40,50,90],[80,100,5]])

array([[ 10,  20,  30],
       [ 40,  50,  90],
       [ 80, 100,   5]])

In [11]:
np.min(b,axis=1) #ในแนวนอน

array([10, 40,  5])

In [12]:
np.min(b,axis = 0) #แนวตั้ง

array([10, 20,  5])